# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f63cd051519b44184c9bfb23d6cc0681808af5571be9101908a99c190dbb39683715885641dbf7695945b3025b36e48e6566238adecc420374d852461454b8b1

test:
  secret_key_base: d436a859f670d8a265b5ea84057b38f3f7e41e02378e16a46336bea69d07c337f258a56ef8989ea347f0e4b1572e1a0bf805a0a1a1f51a8449d2a71bf14210c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
